# Site settings  https://unsplash.com/collections
title: Takumi Matsuzawa
description: 'Physicist / Chemist / Programmer with emphasis on experimental fluid mechanics and big data'

#############
# HTML Head #
#############

lang: "en"
author: "Takumi Matsuzawa"
  Name: "Takumi Matsuzawa"
  email: takumi.matz@gmail.com
  twitter_username: test
  github_username:  tmatsuzawa
  google_scholar_id: geBWMoIAAAAJ


title: "Takumi Matsuzawa"
description: "Physicist / Chemist / Programmer with emphasis on experimental fluid mechanics and big data"
keywords: "Matsuzawa, Takumi, Soft Matter, Physics, The University of Chicago, UChicago, Chicago, Fluid, Fluid Mechanics, Turbulence, Vortex, Vortex rings, Topological"
favicon: "/img/atom_icon.ico"
black-favicon: "/img/atom_icon.ico"
background-img: "../img/intro-bg.JPG"


# NB! Set your site's url, otherwise stuff will break :)
url: "https://tmatsuzawa.github.io"
baseurl:


# Google tracking id

google-tracking-id: "UA-106933616-1"


# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True


# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'



defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
paginate_path: blog/page:num
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
