
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://tmatsuzawa.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Takumi Matsuzawa"
title: "Takumi Matsuzawa"
description: "Website of Takumi Matsuzawa, blogging, personal information as well as information and documentation for different projects."
keywords: "Matsuzawa, Takumi, Soft Matter, Physics, The University of Chicago, UChicago, Chicago, Fluid, Fluid Mechanics"
favicon: "/img/atom_icon.ico"

################
# Header layout #
################

black-favicon: "/img/atom_icon.ico"

background-img: "../img/intro-bg.JPG"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "A life lived in pursuit of excellence is a life well lived. - Harry Messel"
  - text: "Knowing is not enough; we must apply. Willing is not enough; we must do. - Johann Wolfgang von Goethe"
  - text: "Nothing in this world is to be feared... only understood. - Marie Curie"

me-img: "/img/author.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/atom_icon_32.ico"
icon-48p: "/img/web-app/atom_icon_48.ico"
icon-72p: "/img/web-app/atom_icon_64.ico"
icon-96p: "/img/web-app/atom_icon_96.ico"
icon-144p: "/img/web-app/atom_icon_128.ico"
icon-192p: "/img/web-app/atom_icon_192.ico"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "tmatsuzawa"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/ISS_2011.jpg"
    date: "July 2011"
    description: "Participated the International Science School as a national representative (Sydney, Australia)"
 # - image: "/img/timeline/uni_hike.jpg"
 #   date: "April 2012"
 #   description: "Started Yokohama National University (Yokohama, Japan)"
  - image: "/img/timeline/ynfp.jpg"
    date: "May 2012 - March 2013"
    description: "Student Formula Japan- chassis team (Yokohama, Japan)"
  - image: "/img/timeline/kzoo.jpg"
    date: "September 2013"
    description: "Started Kalamazoo College (Kalamazoo, U.S.A.)"
  - image: "/img/timeline/kek.png"
    date: "Summer 2014"
    description: "Laser-Induced Breakdown Spectroscopy (LIBS) (KEK, Japan)"
  - image: "/img/timeline/vaccination.png"
    date: "Summer 2014"
    description: "Efficacy of vaccines through mathematical modeling (Kalamazoo, MI)"

  - image: "/img/timeline/Wilson_Hall.png"
    date: "Summer 2015"
    description: "Lee Teng internship at Fermilab (Batavia, IL)"

  - image: "/img/timeline/melting.png"
    date: "June 2014 - June 2016"
    description: "Melting transition of Yukawa systems through Monte Carlo and Molecular Dynamics simulations (Kalamazoo, MI)"
  - image: "/img/timeline/neuro.jpg"
    date: "Sept 2014 - July 2016"
    description: "Multi-scale modeling of altered synaptic plasticity related to Amyloid Î² effects (Kalamazoo, MI)"

  - image: "/img/timeline/kzoo_grad.png"
    date: "June 2016"
    description: "Graduated from Kalamazoo College (Bogota, Colombia)"


  - image: "/img/timeline/uchicago.jpg"
    date: "September 2016"
    description: "Started a physics Ph.D. program at The University of Chicago (Chicago, IL)"
  - image: "/img/timeline/splashing.png"
    date: "September 2016 - June 2017"
    description: "Characterization of Thin-Sheet Ejection Using Low-Viscosity Fluids (Chicago, IL)"
  - image: "/img/timeline/turbulence.png"
    date: "June 2017 - "
    description: "Joined the Irvine lab with focus on turbulence"



# First image of the Timeline

timeline-img: "/img/timeline/erc.jpg"

###########
# Contact #
###########

email: "tmatsuzawa@uchicago.edu"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Takumi Matsuzawa is a Physics Ph.D. candidate at The University Chicago. In addition to his passion in soft matter, he likes cycling, rock-climbing, and sketching.  "
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/takumi.matsuzawa"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/takumim/"
  - title: "github"
    url: "https://github.com/tmatsuzawa"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: tmatsuzawa
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
