# Site settings  https://unsplash.com/collections
title: Takumi Matsuzawa
description: 'Physicist / Chemist / Programmer'
keywords: "Matsuzawa, Takumi, Soft Matter, Physics, The University of Chicago, UChicago, Chicago, Fluid, Fluid Mechanics"
favicon: "/images/favicons/atom_icon.ico"


url: 'http://tmatsuzawa.github.io'
baseurl:
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'


author:
  name: 'Takumi Matsuzawa'
  email: takumi.matz@gmail.com
  github_username:  tmatsuzawa
  linkedin_username:  takumim
  google_scholar_id: geBWMoIAAAAJ
#  twitter_username:


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
paginate_path: blog/page:num
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
